### ISSUE TITLE
muGrid fails to build on macOS 10.15.8 (Catalina)

### ISSUE THREAD

**Issue by SenileFelineS** [muSpectre/muGrid#153]
Hi,

I am trying to install muGrid, but it doesn't compile on my macOS Catalina 10.15.8 machine.
I am in a `conda` environment and used `pip install muGrid`

Here is the error that I recieve:

```
      In file included from /private/var/folders/g4/zqrmjd_s5nqb0qy6gzdhl88r0000gr/T/pip-install-w8_dozga/mugrid_6fcb11947d6a4f55a043734532859d03/src/libmugrid/field/field.cc:39:
      In file included from /private/var/folders/g4/zqrmjd_s5nqb0qy6gzdhl88r0000gr/T/pip-install-w8_dozga/mugrid_6fcb11947d6a4f55a043734532859d03/src/libmugrid/collection/field_collection_global.hh:40:
      In file included from /private/var/folders/g4/zqrmjd_s5nqb0qy6gzdhl88r0000gr/T/pip-install-w8_dozga/mugrid_6fcb11947d6a4f55a043734532859d03/src/libmugrid/grid/pixels.hh:40:
      In file included from /private/var/folders/g4/zqrmjd_s5nqb0qy6gzdhl88r0000gr/T/pip-install-w8_dozga/mugrid_6fcb11947d6a4f55a043734532859d03/src/libmugrid/core/coordinates.hh:41:
      /private/var/folders/g4/zqrmjd_s5nqb0qy6gzdhl88r0000gr/T/pip-install-w8_dozga/mugrid_6fcb11947d6a4f55a043734532859d03/src/libmugrid/grid/iterators.hh:35:10: fatal error: 'ranges' file not found
      #include <ranges>
               ^~~~~~~~
      1 error generated.
      ninja: build stopped: subcommand failed.
      
      *** CMake build failed
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for muGrid
Failed to build muGrid
error: failed-wheel-build-for-install

× Failed to build installable wheels for some pyproject.toml based projects
╰─> muGrid
```

If I understand correctly, it can't find ranges.
I tried installing the python module ranges-v3 but that didn't fix anything.
I also tried installing `gcc` in my `conda` environment so gcc would be seen in the path before Apple's default `clang`, but that didn't fix it either.

I do have CUDA installed (not the newest version), as well.

Is there anything else I can try?

**Comment by SenileFelineS** [comment]
Okay, I think I know more about what's going on. muGrid is trying to use Apple's default `/usr/bin/clang++`. However, if I could get muGrid to just use `clang` or `gcc` in my `conda` environment, it would use the `conda` installed version (which is up to date).

EDIT: The solution was to install `clangxx` in my `conda` environment.

**Comment by pastewka** [comment]
There should also be macOS wheels, but they don't have CUDA enabled.

**Comment by pastewka** [comment]
The error means your compiler is too old, not that a package is missing: <ranges> is part of the C++20 standard library, which muGrid requires since version 0.97.0. The newest Xcode available on Catalina (12.4, Apple Clang 12) doesn't have it, and since we don't publish Intel-Mac binary wheels, pip falls back to compiling from source. The ranges-v3 Python package is unrelated, and putting gcc on your PATH has no effect — the build picks its compiler from CC/CXX. Also note your CUDA install plays no role here: muGrid's pip build is CPU-only, and CUDA hasn't supported macOS for years.

conda helped you to install a more modern compiler which is what fixed it for you. I've added a guard with a more helpful error message to the CMake script.
